### ISSUE TITLE
Cannot cloning into /robo-vln/environments/habitat-sim/src/deps/imgui

### ISSUE THREAD

**Issue by dee-ex** [GT-RIPL/robo-vln#5]
In the last command to install
```
python setup.py install --headless --with-cuda
```
but it took to long for me to wait. I had tried to rerun `setup.py`, however it still didn't work. 

![image](https://user-images.githubusercontent.com/42053523/133572237-5e506425-a3b5-4916-844d-343d6bfdbde5.png)

Please help me solve this problem.

**Comment by zubair-irshad** [comment]
Can you share the complete error trace? Since we did not encounter any such issues on our end, I would recommend looking into installing habitat-sim instructions and common build issues [here](https://github.com/facebookresearch/habitat-sim/blob/master/BUILD_FROM_SOURCE.md). All the system dependencies need to be met (mentioned in the [instructions](https://github.com/facebookresearch/habitat-sim/blob/master/BUILD_FROM_SOURCE.md) for the installation to be successful)

**Comment by dee-ex** [comment]
I did reinstall from scratch following your README, and pass the cloning part, but still get error in `Install habitat-sim`, here is full respond
```
(habitat) C:\Users\Admin\Desktop\robo-vln\environments\habitat-sim>python setup.py install --headless --with-cuda
running install
running bdist_egg
running egg_info
creating habitat_sim.egg-info
writing habitat_sim.egg-info\PKG-INFO
writing dependency_links to habitat_sim.egg-info\dependency_links.txt
writing requirements to habitat_sim.egg-info\requires.txt
writing top-level names to habitat_sim.egg-info\top_level.txt
writing manifest file 'habitat_sim.egg-info\SOURCES.txt'
reading manifest file 'habitat_sim.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'habitat_sim.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\lib.win-amd64-3.6
creating build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\attributes.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\attributes_managers.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\errors.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\geo.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\gfx.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\logging.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\physics.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\registry.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\scene.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\sensor.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\sim.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\simulator.py -> build\lib.win-amd64-3.6\habitat_sim
copying habitat_sim\__init__.py -> build\lib.win-amd64-3.6\habitat_sim
creating build\lib.win-amd64-3.6\habitat_sim\agent
copying habitat_sim\agent\agent.py -> build\lib.win-amd64-3.6\habitat_sim\agent
copying habitat_sim\agent\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\agent
creating build\lib.win-amd64-3.6\habitat_sim\bindings
copying habitat_sim\bindings\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\bindings
creating build\lib.win-amd64-3.6\habitat_sim\nav
copying habitat_sim\nav\greedy_geodesic_follower.py -> build\lib.win-amd64-3.6\habitat_sim\nav
copying habitat_sim\nav\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\nav
creating build\lib.win-amd64-3.6\habitat_sim\sensors
copying habitat_sim\sensors\sensor_suite.py -> build\lib.win-amd64-3.6\habitat_sim\sensors
copying habitat_sim\sensors\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\sensors
creating build\lib.win-amd64-3.6\habitat_sim\utils
copying habitat_sim\utils\collect_env.py -> build\lib.win-amd64-3.6\habitat_sim\utils
copying habitat_sim\utils\common.py -> build\lib.win-amd64-3.6\habitat_sim\utils
copying habitat_sim\utils\compare_profiles.py -> build\lib.win-amd64-3.6\habitat_sim\utils
copying habitat_sim\utils\profiling_utils.py -> build\lib.win-amd64-3.6\habitat_sim\utils
copying habitat_sim\utils\viz_utils.py -> build\lib.win-amd64-3.6\habitat_sim\utils
copying habitat_sim\utils\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\utils
creating build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\controls.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\default_controls.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\object_controls.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\pyrobot_noisy_controls.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
copying habitat_sim\agent\controls\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\agent\controls
creating build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models
copying habitat_sim\sensors\noise_models\gaussian_noise_model.py -> build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models
copying habitat_sim\sensors\noise_models\no_noise_model.py -> build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models
copying habitat_sim\sensors\noise_models\poisson_noise_model.py -> build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models
copying habitat_sim\sensors\noise_models\redwood_depth_noise_model.py -> build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models
copying habitat_sim\sensors\noise_models\salt_and_pepper_noise_model.py -> build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models
copying habitat_sim\sensors\noise_models\sensor_noise_model.py -> build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models
copying habitat_sim\sensors\noise_models\speckle_noise_model.py -> build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models
copying habitat_sim\sensors\noise_models\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models
creating build\lib.win-amd64-3.6\habitat_sim\utils\data
copying habitat_sim\utils\data\data_extractor.py -> build\lib.win-amd64-3.6\habitat_sim\utils\data
copying habitat_sim\utils\data\data_structures.py -> build\lib.win-amd64-3.6\habitat_sim\utils\data
copying habitat_sim\utils\data\pose_extractor.py -> build\lib.win-amd64-3.6\habitat_sim\utils\data
copying habitat_sim\utils\data\__init__.py -> build\lib.win-amd64-3.6\habitat_sim\utils\data
creating build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models\data
copying habitat_sim\sensors\noise_models\data\redwood-depth-dist-model.npy -> build\lib.win-amd64-3.6\habitat_sim\sensors\noise_models\data
running build_ext
Submodule 'docs/m.css' (https://github.com/mosra/m.css) registered for path 'docs/m.css'
Submodule 'src/deps/Sophus' (https://github.com/strasdat/Sophus) registered for path 'src/deps/Sophus'
Submodule 'src/deps/assimp' (https://github.com/assimp/assimp) registered for path 'src/deps/assimp'
Submodule 'src/deps/corrade' (https://github.com/mosra/corrade.git) registered for path 'src/deps/corrade'
Submodule 'src/deps/eigen-git-mirror' (https://github.com/eigenteam/eigen-git-mirror) registered for path 'src/deps/eigen-git-mirror'
Submodule 'src/deps/glfw' (https://github.com/glfw/glfw) registered for path 'src/deps/glfw'
Submodule 'src/deps/glog' (https://github.com/google/glog.git) registered for path 'src/deps/glog'
Submodule 'src/deps/googletest' (https://github.com/google/googletest) registered for path 'src/deps/googletest'
Submodule 'src/deps/imgui' (https://github.com/ocornut/imgui.git) registered for path 'src/deps/imgui'
Submodule 'src/deps/magnum' (https://github.com/mosra/magnum.git) registered for path 'src/deps/magnum'
Submodule 'src/deps/magnum-bindings' (https://github.com/mosra/magnum-bindings.git) registered for path 'src/deps/magnum-bindings'
Submodule 'src/deps/magnum-integration' (https://github.com/mosra/magnum-integration.git) registered for path 'src/deps/magnum-integration'
Submodule 'src/deps/magnum-plugins' (https://github.com/mosra/magnum-plugins.git) registered for path 'src/deps/magnum-plugins'
Submodule 'src/deps/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'src/deps/pybind11'
Submodule 'src/deps/rapidjson' (https://github.com/Tencent/rapidjson.git) registered for path 'src/deps/rapidjson'
Submodule 'src/deps/recastnavigation' (https://github.com/erikwijmans/recastnavigation.git) registered for path 'src/deps/recastnavigation'
Submodule 'src/deps/tinyobjloader' (https://github.com/syoyo/tinyobjloader.git) registered for path 'src/deps/tinyobjloader'
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/docs/m.css'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/Sophus'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/assimp'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/corrade'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/eigen-git-mirror'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/glfw'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/glog'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/googletest'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/imgui'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/magnum'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/magnum-bindings'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/magnum-integration'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/magnum-plugins'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/pybind11'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/rapidjson'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/recastnavigation'...
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/tinyobjloader'...
Submodule path 'docs/m.css': checked out '01ea5ad52eb8e85b018027a5d540f5822ebfebba'
Submodule path 'src/deps/Sophus': checked out 'b475c0a81a197ff8ea6bdcf8df8a2f5a7b1da879'
Submodule path 'src/deps/assimp': checked out '8f0c6b04b2257a520aaab38421b2e090204b69df'
Submodule path 'src/deps/corrade': checked out '71624bcdf10a23b60eb9dceda9434d9d7593799e'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/corrade/toolchains'
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/corrade/toolchains'...
Submodule path 'src/deps/corrade/toolchains': checked out '03a6b4c2648e9b367b2e8eef4b869a3d7c47c16f'
Submodule path 'src/deps/eigen-git-mirror': checked out 'd10e1f03d4ef456f78ff6b91d9078b1f13a5975c'
Submodule path 'src/deps/glfw': checked out '0a49ef0a00baa3ab520ddc452f0e3b1e099c5589'
Submodule path 'src/deps/glog': checked out '8d7a107d68c127f3f494bb7807b796c8c5a97a82'
Submodule path 'src/deps/googletest': checked out '00938b2b228f3b70d3d9e51f29a1505bdad43f1e'
Submodule path 'src/deps/imgui': checked out 'ca30ef4269150e71a950106c6cfa8f94898581da'
Submodule path 'src/deps/magnum': checked out '8c5a2d6a88392e6bf6b280d8bc04ee6ed695bdcc'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/magnum/toolchains'
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/magnum/toolchains'...
Submodule path 'src/deps/magnum/toolchains': checked out '03a6b4c2648e9b367b2e8eef4b869a3d7c47c16f'
Submodule path 'src/deps/magnum-bindings': checked out '66681d4dee950fe48fcbdd2a7e45a76e4480a4ec'
Submodule path 'src/deps/magnum-integration': checked out 'f148cd9cdbe3f1b6b17ca2f7dc5a1531a651533c'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/magnum-integration/toolchains'
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/magnum-integration/toolchains'...
Submodule path 'src/deps/magnum-integration/toolchains': checked out 'fe0e99114811d646617322667ec6abba018ddaed'
Submodule path 'src/deps/magnum-plugins': checked out 'c669efd2d67db50f1a8ac5c0776de3b8ae7bea93'
Submodule 'toolchains' (https://github.com/mosra/toolchains.git) registered for path 'src/deps/magnum-plugins/toolchains'
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/magnum-plugins/toolchains'...
Submodule path 'src/deps/magnum-plugins/toolchains': checked out 'fe0e99114811d646617322667ec6abba018ddaed'
Submodule path 'src/deps/pybind11': checked out 'e43e1cc01ae6d4e4e5ba10557a057d7f3d5ece0d'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'src/deps/pybind11/tools/clang'
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/pybind11/tools/clang'...
Submodule path 'src/deps/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'src/deps/rapidjson': checked out '73063f5002612c6bf64fe24f851cd5cc0d83eef9'
Submodule 'thirdparty/gtest' (https://github.com/google/googletest.git) registered for path 'src/deps/rapidjson/thirdparty/gtest'
Cloning into 'C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/src/deps/rapidjson/thirdparty/gtest'...
Submodule path 'src/deps/rapidjson/thirdparty/gtest': checked out '0a439623f75c029912728d80cb7f1b8b48739ca4'
Submodule path 'src/deps/recastnavigation': checked out '354591e10a772b8057e42a4f9de701155b9aaa02'
Submodule path 'src/deps/tinyobjloader': checked out 'e52dfdbecdf8893b161a65e508bc009746fa6042'
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:12 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:12 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:12 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/build/Release/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Admin/Desktop/robo-vln/environments/habitat-sim/build/Release/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 390, in <module>
    include_package_data=True,
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 204, in run
    self.build_extension(ext)
  File "setup.py", line 273, in build_extension
    env=env,
  File "C:\Users\Admin\anaconda3\envs\habitat\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-HC:\\Users\\Admin\\Desktop\\robo-vln\\environments\\habitat-sim\\src', '-Bbuild\\Release', '-DBUILD_PYTHON_BINDINGS=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Admin\\Desktop\\robo-vln\\environments\\habitat-sim\\build\\lib.win-amd64-3.6\\habitat_sim\\_ext', '-DPYTHON_EXECUTABLE=C:\\Users\\Admin\\anaconda3\\envs\\habitat\\python.exe', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-GNinja', '-DBUILD_GUI_VIEWERS=OFF', '-DBUILD_TEST=OFF', '-DBUILD_WITH_BULLET=OFF', '-DBUILD_DATATOOL=OFF', '-DBUILD_WITH_CUDA=ON']' returned non-zero exit status 1.
```

**Comment by zubair-irshad** [comment]
I would recommend checking your CUDA installation again and if it is included in your CMAKE path. The following lines from your error trace would be able to help you: 

> CMake Error at CMakeLists.txt:12 (project):
> No CMAKE_CUDA_COMPILER could be found.
> 
> Tell CMake where to find the compiler by setting either the environment
> variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
> path to the compiler, or to the compiler name if it is in the PATH.

Also please note that this error is not related to our codebase robo-vln, rather there exists a separate codebase just to maintain the habitat-sim repo. Please direct your questions [here](https://github.com/facebookresearch/habitat-sim/issues) (or look for similar closed issues on the [habitat-sim](https://github.com/facebookresearch/habitat-sim/issues?q=is%3Aissue+is%3Aclosed) repo). Thanks!
